# Correlations and statistics

**Objective :**
- Determine if habitat type has a significant effect on life history (PC1)
- Determine if taxonomic classes has a significant effect on life history

**Analyses performed :**
- T-test
- ANOVA

In [2]:
import pandas as pd
import plotly.express as px
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.multicomp as mc
from statsmodels.stats.multicomp import tukeyhsd
from scipy.stats import ttest_ind

## T-test : Effect of habitat type on life history

In [3]:
df= pd.read_csv('../data/new_habitat.csv')
display(df.head())

aquatic = df[df['habitat'] == "A"]['PC1']
terrestrial = df[df['habitat'] == "T"]['PC1']

                       Species       PC1 habitat
0  Symsagittifera_roscoffensis -4.332599       A
1      Aequipecten_opercularis -2.418778       A
2            Mimachlamys_varia -2.773367       A
3               Mytilus_edulis -2.602300       A
4           Panopea_abbreviata -0.460463       A

**Hypothesis :**
- H0: No significant effect of the habitat on life history
- H1: There is a significant effect of the habitat on life history

In [4]:
# Test for normality
stat, p = stats.shapiro(df['PC1'])  
print(f"Shapiro-Wilk test: Statistic={stat}, p-value={p}")

Shapiro-Wilk test: Statistic=0.9579976327808482, p-value=2.628020458087804e-17

p-value = 2.63e-17 < 0.05 -> the data does not follow a normal distribution

We still do the t-test

In [5]:
# boxplot 
fig = px.box(
    df,
    x="habitat",         
    y="PC1",           
    color="habitat",
    color_discrete_sequence=px.colors.qualitative.Set2,
    # category_orders={"Class": ordered_classes},
)

fig.update_layout(
    title="Boxplot of PC1 by habitat",
    xaxis_title="Habitat",
    yaxis_title="PC1",
    height=600
)

fig.show()

In [6]:
# t-test
stat, p = stats.ttest_ind(aquatic,
                          terrestrial,
                          equal_var=True)  
print(f"Independent t-test: Statistic={stat}, p-value={p}")

Independent t-test: Statistic=-5.035889812391533, p-value=5.56338439116844e-07

p-value = 5.56e-07 < 0.05 -> There is a significant difference in PC1 between aquatic and terrestrial habitat

The negative sign suggests PC1 is lower for aquatic habitats compared to terrestrial ones and that corresponds to the plot

## ANOVA: Effect of taxonomic classes on life history

In [7]:
df_species = pd.read_csv("../data/species.csv")
df_pca = pd.read_csv("../data/pca.csv")

df = pd.merge(df_species, df_pca, on='Species')
df = df.drop(columns=["ScientificName", "Mod", "MRE", "SMSE", "COM", "rest", "PC2"])
chordata_data = df[df['Phylum'] == 'Chordata']

chordata_data.head()

,Species,Phylum,Class,Order,Family,CommonName,PC1
66,Branchiostoma_floridae,Chordata,Leptocardii,Amphioxiformes,Branchiostomidae,Florida lancelet,-2.659253
67,Ascidiella_aspersa,Chordata,Ascidiacea,Phlebobranchia,Ascidiidae,European sea squirt,-3.010048
68,Boltenia_echinata,Chordata,Ascidiacea,Stolidobranchia,Pyuridae,Cactus sea squirt,-1.231608
69,Styela_plicata,Chordata,Ascidiacea,Stolidobranchia,Styelidae,Pleated sea squirt,-3.595991
70,Hemiscyllium_ocellatum,Chordata,Chondrichthyes,Orectolobiformes,Hemiscylliidae,Epaulette shark,2.833690

In [8]:
# boxplot
ordered_classes = (
    chordata_data.groupby("Class")["PC1"]
    .median()
    .sort_values()
    .index.tolist()
)

fig = px.box(
    chordata_data,
    x="Class",         
    y="PC1",           
    color="Class",     
    color_discrete_sequence=px.colors.qualitative.Set2,
    # category_orders={"Class": ordered_classes},
)

fig.update_layout(
    title="Boxplot of PC1 by class",
    xaxis_title="Class",
    yaxis_title="PC1",
    height=600
)

fig.show()
# fig.write_html("../figures/boxplot_class.html")

**Observations**  
Some taxonomic classes have very few species (Leptocardii and Mammalia), making the ANOVA results less reliable.

In [9]:
# Anova
model = smf.ols('PC1 ~ Class', data=chordata_data).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)

               sum_sq      df           F         PR(>F)
Class     1273.153491     7.0  152.330453  2.618877e-154
Residual  1234.572306  1034.0         NaN            NaN

p-value < 0,05 - > There is a significant effect of taxonomic class on life history. 

This suggests that at least one taxonomic class show a statistically different life history strategy compared to others within Chordata.  

To identify where are these differences, we perform a Tukey's multiple comparisons test to compare all taxonomic classes pairwise.

In [10]:
# Tukey's test

tukey = mc.MultiComparison(chordata_data["PC1"], chordata_data["Class"])
tukey_result = tukey.tukeyhsd()

print(tukey_result)

        Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================================
    group1         group2     meandiff p-adj   lower   upper  reject
--------------------------------------------------------------------
Actinopterygii       Amphibia   0.0275    1.0 -0.3009  0.3559  False
Actinopterygii     Ascidiacea  -2.2444 0.0095 -4.1645 -0.3244   True
Actinopterygii           Aves   2.4183    0.0  1.8855  2.9511   True
Actinopterygii Chondrichthyes   4.2337    0.0  3.6249  4.8424   True
Actinopterygii    Leptocardii  -2.2911 0.4186 -5.6121  1.0298  False
Actinopterygii       Mammalia   2.3811 0.0444  0.0312   4.731   True
Actinopterygii       Reptilia   2.3892    0.0  2.0677  2.7108   True
      Amphibia     Ascidiacea   -2.272 0.0093  -4.212 -0.3319   True
      Amphibia           Aves   2.3908    0.0  1.7898  2.9918   True
      Amphibia Chondrichthyes   4.2062    0.0   3.537  4.8754   True
      Amphibia    Leptocardii  -2.3187  0.407 -5.6512  1.0139  False
      Amphibia       Mammalia   2.3536 0.0524 -0.0127  4.7198  False
      Amphibia       Reptilia   2.3617    0.0  1.9367  2.7867   True
    Ascidiacea           Aves   4.6627    0.0  2.6779  6.6476   True
    Ascidiacea Chondrichthyes   6.4781    0.0  4.4715  8.4847   True
    Ascidiacea    Leptocardii  -0.0467    1.0 -3.8787  3.7853  False
    Ascidiacea       Mammalia   4.6255 0.0001   1.596   7.655   True
    Ascidiacea       Reptilia   4.6337    0.0  2.6948  6.5725   True
          Aves Chondrichthyes   1.8154    0.0  1.0255  2.6052   True
          Aves    Leptocardii  -4.7095 0.0006 -8.0683 -1.3506   True
          Aves       Mammalia  -0.0372    1.0 -2.4404   2.366  False
          Aves       Reptilia  -0.0291    1.0 -0.6264  0.5682  False
Chondrichthyes    Leptocardii  -6.5248    0.0 -9.8966 -3.1531   True
Chondrichthyes       Mammalia  -1.8526 0.2814 -4.2737  0.5686  False
Chondrichthyes       Reptilia  -1.8445    0.0 -2.5103 -1.1786   True
   Leptocardii       Mammalia   4.6722 0.0117  0.6077  8.7367   True
   Leptocardii       Reptilia   4.6804 0.0006  1.3485  8.0123   True
      Mammalia       Reptilia   0.0081    1.0 -2.3572  2.3735  False
--------------------------------------------------------------------

In [11]:
group_letters = {
    'Actinopterygii': 'a',
    'Amphibia': 'ab',
    'Leptocardii': 'ac',
    'Ascidiacea': 'c',
    'Aves': 'd',
    'Mammalia': 'bde',
    'Chondrichthyes': 'e',
    'Reptilia': 'd'
}

In [12]:
fig = px.box(
    chordata_data,
    x="Class",         
    y="PC1",           
    color="Class",     
    color_discrete_sequence=px.colors.qualitative.Set2,
    # category_orders={"Class": ordered_classes},
)

y_positions = chordata_data.groupby("Class")["PC1"].max() + 0.5  

for cls, y in y_positions.items():
    fig.add_annotation(
        x=cls,
        y=y,
        text=group_letters.get(cls, ''),
        showarrow=False,
        font=dict(size=14, color='black'),
        yanchor="bottom"
    )

fig.update_layout(
    title="Boxplot of PC1 by class",
    xaxis_title="Class",
    yaxis_title="PC1",
    height=600
)

fig.show()
fig.write_html("../figures/boxplot_class_tukey.html")

**Interpretations**  
- Classes that share a letter are not significantly different.
- Classes with no letters in common are significantly different.  

**Leptocardii** and **Ascidiacea** are not significantly different and correspond to faster life history strategies.  
 
**Reptilia**, **Aves** and **Mammalia** are not significantly different and correspond to slower life history startegies.  

**Chrondrichthyes** is not significantly different from **Mammalia** and has the highest values of PC1, wich correspond to slow life history strategies.

## ANOVA: Effect of food type at adult stage on life history

In [17]:
df_food = pd.read_csv("../data/fooddf.csv")
#change nae ID by Species
df_food = df_food.rename(columns={"ID": "Species"})

df = pd.merge(df_food, df_pca, on='Species')
df = df.drop(columns=["PC2", "startdev", "death"])

df_single_food = df[df['adult'].notna() & (df['adult'].str.len() == 1)].copy()

df_single_food.head()

                   Species birth weaning juvenile adult pupa       PC1
1  Aequipecten_opercularis     P       P        P     P    P -2.418778
2        Mimachlamys_varia     P       P        P     P    P -2.773367
3           Mytilus_edulis     P       P        P     P    P -2.602300
4       Panopea_abbreviata     P       P        H     H    H -0.460463
6          Donax_trunculus     P       P        D     D    D -2.544785

In [18]:
# boxplot

fig = px.box(
    df_single_food,
    x="adult",         
    y="PC1",           
    color="adult",     
    color_discrete_sequence=px.colors.qualitative.Set2,
)

fig.update_layout(
    title="Boxplot of PC1 by food type",
    xaxis_title="Food type",
    yaxis_title="PC1",
    height=600
)

fig.show()

In [19]:
# Anova
model = smf.ols('PC1 ~ adult', data=df_single_food).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print(anova_table)

               sum_sq     df          F        PR(>F)
adult      373.675659    5.0  34.367496  2.416414e-32
Residual  2063.683673  949.0        NaN           NaN

p-value = 2.416414e-32 < 0,05 -> There is a significant effect of food type on life history. 

At least one food type show a statistically different life history strategy compared to others.  

We perform a Tukey's multiple comparisons test to compare all food types pairwise.

In [20]:
# Tukey's test

tukey = mc.MultiComparison(df_single_food["PC1"], df_single_food["adult"])
tukey_result = tukey.tukeyhsd()

print(tukey_result)

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     C      D  -1.7408 0.0004  -2.9195 -0.5622   True
     C      H    0.739 0.0503  -0.0005  1.4784  False
     C      O   0.2242 0.9817  -0.6875   1.136  False
     C      P  -1.3391    0.0  -1.6893 -0.9889   True
     C      T  -7.0911    0.0  -11.305 -2.8772   True
     D      H   2.4798    0.0   1.1066  3.8529   True
     D      O   1.9651 0.0021    0.492  3.4382   True
     D      P   0.4018 0.9335  -0.8071  1.6107  False
     D      T  -5.3503 0.0065  -9.7202 -0.9804   True
     H      O  -0.5147 0.7984  -1.6669  0.6375  False
     H      P   -2.078    0.0  -2.8648 -1.2913   True
     H      T  -7.8301    0.0 -12.1025 -3.5577   True
     O      P  -1.5633    0.0  -2.5138 -0.6128   True
     O      T  -7.3154    0.0 -11.6209 -3.0098   True
     P      T   -5.752 0.0015  -9.9745 -1.5296   True
-----------------------------------------------------

In [21]:
group_letters = {
    'C': 'a',
    'D': 'b',
    'H': 'a',
    'O': 'b',
    'P': 'a',
    'T': 'c',
}

In [23]:
fig = px.box(
    df_single_food,
    x="adult",         
    y="PC1",           
    color="adult",     
    color_discrete_sequence=px.colors.qualitative.Set2,
)

y_positions = df_single_food.groupby("adult")["PC1"].max() + 0.5  

for cls, y in y_positions.items():
    fig.add_annotation(
        x=cls,
        y=y,
        text=group_letters.get(cls, ''),
        showarrow=False,
        font=dict(size=14, color='black'),
        yanchor="bottom"
    )

fig.update_layout(
    title="Boxplot of PC1 by food type",
    xaxis_title="Food type",
    yaxis_title="PC1",
    height=600
)

fig.show()
fig.write_html("../figures/boxplot_food_tukey.html")

**Interpretations**   

- **T** (parasitic) is significantly different from every others food types and correspond to faster life history stategies.
 
- **P** (planktivore), **H** (herbivore) and **C** (carnivore) are not significantly different from each other and tend to follow slower life history strategies.

- **D** (detrivore) and **O** (omnivore) are not significantly different.